apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  # Tipe Secret Opaque digunakan untuk data yang tidak akan dienkripsi.
type: Opaque
data:
#username pasword yg di enkripsi
  MONGO_ROOT_USERNAME: YWRtaW4= 
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA== 